[versions]
flyway = "9.22.3"
junit = "5.10.0"
spotless = "6.23.3"


[libraries]
junit-jupiter-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
