[versions]
flyway = "9.22.3"
junit = "5.10.0"
postgre = "42.5.0"
spotless = "6.23.3"
testcontainers = "1.19.8"


[libraries]
junit-jupiter-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
postgresql= {module = "org.postgresql:postgresql", version.ref = "postgre"}
testcontatiners = {module = "org.testcontainers:postgresql", version.ref = "testcontainers"}

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
