[versions]
junit = "5.10.0"
spotless = "6.23.3"

[libraries]
junit-jupiter-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
